---
title: "Whole Exome Sequencing"
author: "Shubham Agrawal"
date: "2026-06-16"
output:
  BiocStyle::html_document:
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

```{r}
wes <- read_excel("/Users/shubhamagrawal/Desktop/ALL/data/wes/combined_report.xlsx")
head(wes)
```

```{r}
snv_mat <- wes %>%
  mutate(
    SNV = ifelse(is.na(SNV_Consequence), 0, 1)
  ) %>%
  select(Sample, Gene, SNV) %>%
  pivot_wider(
    names_from = Sample,
    values_from = SNV,
    values_fill = 0
  )

head(snv_mat)
dim(snv_mat)
```

```{r}
snv <- as.data.frame(snv_mat)
rownames(snv) <- snv$Gene
snv$Gene <- NULL
head(snv)
```

```{r}
unique(wes$Copy_Number)
```


```{r}
cnv_long <- wes %>%
  mutate(
    DEL = as.integer(grepl("DEL", Combined_class)),
    DUP = as.integer(grepl("DUP", Combined_class))
  ) %>%
  select(Sample, Gene, DEL, DUP) %>%
  pivot_longer(
    cols = c(DEL, DUP),
    names_to = "CNV_type",
    values_to = "Value"
  ) %>%
  mutate(
    Feature = paste(Gene, CNV_type, sep = "_")
  )
```

```{r}
head(cnv_long)
```
```{r}
cnv_binary <- cnv_long %>%
  select(Feature, Sample, Value) %>%
  pivot_wider(
    names_from = Sample,
    values_from = Value,
    values_fill = 0
  )

head(cnv_binary)
```
```{r}
cnv_binary_df <- as.data.frame(cnv_binary)

rownames(cnv_binary_df) <- cnv_binary_df$Feature
cnv_binary_df$Feature <- NULL

head(cnv_binary_df)
```

```{r}
cnv_binary_df[] <- lapply(cnv_binary_df, as.numeric)
```

```{r}
saveRDS(snv, "snvWES.rds")
saveRDS(cnv_binary_df, "cnvWES.rds")
```



```{r}
dim(cnv_binary_df)
# filter out low frequency events
event_freq <- rowSums(cnv_binary_df)
cnv_binary_filt <- cnv_binary_df[event_freq >= 2, ]
dim(cnv_binary_filt)
```


```{r}
wes2 <- wes %>%
  mutate(
    CN = case_when(
      Copy_Number == "0"   ~ 0,
      Copy_Number == "1"   ~ 1,
      Copy_Number == "3"   ~ 3,
      Copy_Number == "4"   ~ 4,
      Copy_Number == "0/3" ~ NA,
      Copy_Number == "1/3" ~ NA,
      is.na(Copy_Number)   ~ NA
    )
  )

head(wes2)
```

```{r}
cnv_values <- wes2 %>%
  select(Sample, Gene, CN) %>%
  pivot_wider(
    names_from = Sample,
    values_from = CN
  )

head(cnv_values)
```

```{r}
cnv_values <- as.data.frame(cnv_values)
rownames(cnv_values) <- cnv_values$Gene
cnv_values$Gene <- NULL
head(cnv_values)
```

```{r}
saveRDS(cnv_values, "cnvRealValues.Rds")
```

