---
title: "Drug and CNV/SNV association"
author: "Shubham Agrawal"
date: "2026-07-03"
output:
  BiocStyle::html_document:
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(limma)
library(ggplot2)
```

# Load the objects

```{r}
drug <- readRDS("objects/drpObject.Rds")
snv <- readRDS("objects/snvWES.rds")
cnv <- readRDS("objects/cnvWES.rds")
cnvOG <- readRDS("objects/cnvRealValues.Rds")
```

# Load the metadata file

```{r}
meta <- read_csv("finalMetadata_Mofa.csv")
meta$drugSample <- as.character(meta$drugSample)
head(meta)
meta <- meta[meta$diseaseType == "T-ALL", ]
head(meta)
```

```{r}
metaSNV <- subset(meta,
                   wesSample %in% colnames(snv) &
                   drugSample %in% colnames(drug))

snv1 <- snv[, metaSNV$wesSample]
drug1 <- drug[, metaSNV$drugSample]

# Rename to common IDs
colnames(snv1) <- metaSNV$drugSample
colnames(drug1) <- metaSNV$drugSample

identical(colnames(snv1), colnames(drug1))
```
```{r}
drug1 <- as.matrix(assay(drug1))

results <- list()

for(gene in rownames(snv1)){

    mut <- factor(snv1[gene,],
                  levels=c(0,1),
                  labels=c("WT","Mut"))

    if(length(unique(mut))<2)
        next
    if (min(table(mut)) < 3)
        next

    design <- model.matrix(~mut)

    fit <- lmFit(drug1, design)
    fit <- eBayes(fit)

    tt <- topTable(fit,
                   coef="mutMut",
                   number=Inf)

    tt$Gene <- gene
    tt$Drug <- rownames(tt)

    results[[gene]] <- tt
}

results <- do.call(rbind, results)
results$GlobalFDR <- p.adjust(results$P.Value, method = "BH")
```



```{r}
results$Sig <- results$GlobalFDR < 0.1
ggplot(results,
       aes(x = logFC,
           y = -log10(P.Value))) +
    geom_point(alpha = 0.5) +
    geom_hline(yintercept = -log10(0.05),
               linetype = 2,
               colour = "red") +
    theme_classic()
```
```{r}
## Heatmap values (logFC)
heat <- results |>
    select(Gene, Drug, logFC) |>
    pivot_wider(names_from = Drug,
                values_from = logFC,
                values_fill = 0)

mat <- as.matrix(heat[, -1])
rownames(mat) <- heat$Gene

## Matrix of significance symbols
sig <- results |>
    mutate(star = case_when(
        P.Value < 0.001 ~ "***",
        P.Value < 0.01  ~ "**",
        P.Value < 0.05  ~ "*",
        TRUE ~ ""
    )) |>
    select(Gene, Drug, star) |>
    pivot_wider(names_from = Drug,
                values_from = star,
                values_fill = "")

sig_mat <- as.matrix(sig[, -1])
rownames(sig_mat) <- sig$Gene

pheatmap(
    mat,
    color = colorRampPalette(c("blue", "white", "red"))(100),
    display_numbers = sig_mat,
    number_color = "black",
    fontsize_number = 10)
```

```{r}
metaCNV <- subset(meta,
                   wesSample %in% colnames(cnv) &
                   drugSample %in% colnames(drug))

cnv2 <- cnv[, metaCNV$wesSample]
drug2 <- drug[, metaCNV$drugSample]

# Rename to common IDs
colnames(cnv2) <- metaCNV$drugSample
colnames(drug2) <- metaCNV$drugSample

identical(colnames(cnv2), colnames(drug2))
```
```{r}
drug2 <- as.matrix(assay(drug2))

results <- list()

for(gene in rownames(cnv2)){

    mut <- factor(cnv2[gene,],
                  levels=c(0,1),
                  labels=c("WT","Mut"))

    if(length(unique(mut))<2)
        next
    if (min(table(mut)) < 3)
        next

    design <- model.matrix(~mut)

    fit <- lmFit(drug2, design)
    fit <- eBayes(fit)

    tt <- topTable(fit,
                   coef="mutMut",
                   number=Inf)

    tt$Gene <- gene
    tt$Drug <- rownames(tt)

    results[[gene]] <- tt
}

results <- do.call(rbind, results)
results$GlobalFDR <- p.adjust(results$P.Value, method = "BH")
```

```{r}
results$Sig <- results$GlobalFDR < 0.1
ggplot(results,
       aes(x = logFC,
           y = -log10(P.Value))) +
    geom_point(alpha = 0.5) +
    geom_hline(yintercept = -log10(0.05),
               linetype = 2,
               colour = "red") +
    theme_classic()
```

```{r}
heat <- results |>
    select(Gene, Drug, logFC) |>
    pivot_wider(names_from = Drug,
                values_from = logFC,
                values_fill = 0)

mat <- as.matrix(heat[,-1])
rownames(mat) <- heat$Gene

pheatmap(mat,
         color = colorRampPalette(c("blue","white","red"))(100))
```

```{r}
ggplot(results,
       aes(Drug,
           Gene)) +
    geom_point(aes(size = -log10(P.Value),
                   colour = logFC)) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    scale_colour_gradient2(low = "blue",
                           mid = "white",
                           high = "red")
```

```{r}
## Heatmap values (logFC)
heat <- results |>
    select(Gene, Drug, logFC) |>
    pivot_wider(names_from = Drug,
                values_from = logFC,
                values_fill = 0)

mat <- as.matrix(heat[, -1])
rownames(mat) <- heat$Gene

## Matrix of significance symbols
sig <- results |>
    mutate(star = case_when(
        P.Value < 0.001 ~ "***",
        P.Value < 0.01  ~ "**",
        P.Value < 0.05  ~ "*",
        TRUE ~ ""
    )) |>
    select(Gene, Drug, star) |>
    pivot_wider(names_from = Drug,
                values_from = star,
                values_fill = "")

sig_mat <- as.matrix(sig[, -1])
rownames(sig_mat) <- sig$Gene

pheatmap(
    mat,
    color = colorRampPalette(c("blue", "white", "red"))(100),
    display_numbers = sig_mat,
    number_color = "black",
    fontsize_number = 10)
```









```{r}
# tt <- topTable(fit,
#                coef = "mutMut",
#                number = Inf)
# 
# tt$Drug <- rownames(tt)
# 
# ggplot(tt, aes(logFC, -log10(adj.P.Val))) +
#     geom_point() +
#     geom_vline(xintercept = 0, linetype = 2) +
#     geom_hline(yintercept = -log10(0.05), linetype = 2) +
#     theme_classic() +
#     xlab("Difference in logAUC") +
#     ylab("-log10(FDR)")
```
```{r}
# results$Drug <- str_remove(rownames(results),
#                            paste0("^", results$Gene, "\\."))
# 
# heat <- results |>
#     select(Gene, Drug, B) |>
#     pivot_wider(names_from = Drug,
#                 values_from = B)
# 
# mat <- as.matrix(heat[,-1])
# rownames(mat) <- heat$Gene
# pheatmap(mat,
#          color = colorRampPalette(c("blue","white","red"))(100))
```





